[tasks."dev:create-image"]
run = 'podman build -t docker.io/tasuki/pi-go-sleep:latest -f Containerfile.dev .'

[tasks."dev:serve"]
run = 'mkdir -p dist && serve dist -p 5733 --single'

[tasks."dev:build"]
run = """
watchexec --restart --verbose \
  --wrap-process=session --exts=elm --debounce=100ms \
  -- ./scripts/build.sh --debug
"""

[tasks.dev]
depends = ["dev:build", "dev:serve"]

[tasks.build]
run = './scripts/build.sh'

[tasks.test]
run = 'elm-test'
